In [8]:
import re 
import sys 
import os 
import numpy as np 
import pandas as pd 
import tensorflow as tf 
import time 
from math import log2

In [9]:
# 1. https://www.tensorflow.org/text/tutorials/text_generation
# 2. https://www.thepythoncode.com/article/text-generation-keras-python
# 3. https://www.kaggle.com/code/hommelette/neural-language-model-with-tensorflow

In [10]:
lang  = 'cwe' # 'sw'
path_file = os.path.join('data', lang+'-train.txt')
cwe = open(path_file, 'r').read().lower()
cwe_decoded =  open(path_file, 'rb').read().decode(encoding = 'utf-8')


In [11]:
unique_chars = ' !"\'(),-.0123456789:;?abcdefghijklmnopqrstuvwxyz'

In [12]:
character_list = re.findall(r"[%s]"%unique_chars, cwe_decoded)

In [13]:
chars = tf.strings.unicode_split(cwe_decoded.split(), input_encoding='UTF-8')

In [14]:
chars[0]

<tf.Tensor: shape=(7,), dtype=string, numpy=array([b'c', b'h', b'i', b'k', b'a', b'l', b'e'], dtype=object)>

In [15]:
ids_from_chars = tf.keras.layers.StringLookup(
    vocabulary=list(unique_chars), mask_token=None)

In [16]:
ids = ids_from_chars(chars)
ids

<tf.RaggedTensor [[25, 30, 31, 33, 23, 34, 27], [44, 31, 36, 37, 29, 31, 34, 27],
 [28, 23, 36, 23], ..., [36, 47, 31, 36, 29, 31], [33, 43, 28, 37, 41, 23],
 [45, 37, 41, 27, 9]]>

In [17]:
chars_from_ids = tf.keras.layers.StringLookup(
    vocabulary=ids_from_chars.get_vocabulary(), invert=True, mask_token=None)


In [18]:
chars = chars_from_ids(ids)
chars

<tf.RaggedTensor [[b'c', b'h', b'i', b'k', b'a', b'l', b'e'],
 [b'v', b'i', b'n', b'o', b'g', b'i', b'l', b'e'],
 [b'f', b'a', b'n', b'a'], ..., [b'n', b'y', b'i', b'n', b'g', b'i'],
 [b'k', b'u', b'f', b'o', b's', b'a'], [b'w', b'o', b's', b'e', b'.']]>

In [19]:
tf.strings.reduce_join(chars, axis=-1).numpy()


array([b'chikale', b'vinogile', b'fana', ..., b'nyingi', b'kufosa',
       b'wose.'], dtype=object)

In [20]:
def text_from_ids(ids):
    return tf.strings.reduce_join(chars_from_ids(ids), axis = -1)

In [21]:
all_ids = ids_from_chars(tf.strings.unicode_split(cwe_decoded, 'UTF-8'))
all_ids

<tf.Tensor: shape=(603432,), dtype=int64, numpy=array([25, 30, 31, ..., 27,  9,  0])>

In [22]:
ids_dataset = tf.data.Dataset.from_tensor_slices(all_ids)


In [23]:
for ids in ids_dataset.take(10):
    print(chars_from_ids(ids).numpy().decode('utf-8'))


c
h
i
k
a
l
e
 
v
i


In [24]:
seq_length = 100

In [25]:
sequences = ids_dataset.batch(seq_length+1, drop_remainder=True)

for seq in sequences.take(1):
    print(chars_from_ids(seq))

tf.Tensor(
[b'c' b'h' b'i' b'k' b'a' b'l' b'e' b' ' b'v' b'i' b'n' b'o' b'g' b'i'
 b'l' b'e' b' ' b'f' b'a' b'n' b'a' b' ' b'v' b'i' b'y' b'a' b' ' b'w'
 b'a' b'n' b'h' b'u' b' ' b'w' b'o' b'c' b'h' b'i' b'k' b'a' b'l' b'a'
 b' ' b'h' b'a' b'b' b'u' b'n' b'g' b"'" b'h' b'u' b'k' b'e' b' ' b'i'
 b'm' b'i' b's' b'i' b',' b' ' b's' b'i' b' ' b'k' b'w' b'a' b' ' b'u'
 b'm' b'e' b'l' b'o' b' ' b'n' b'a' b' ' b'u' b'n' b'g' b"'" b'w' b'a'
 b'j' b'i' b' ' b'n' b'a' b' ' b'u' b'n' b'y' b'o' b'l' b'o' b'd' b'o'
 b' ' b'n' b'a'], shape=(101,), dtype=string)


In [26]:
for seq in sequences.take(5):
    print(text_from_ids(seq).numpy())

b"chikale vinogile fana viya wanhu wochikala habung'huke imisi, si kwa umelo na ung'waji na unyolodo na"
b' uwashelati na ndwagi hebu migongo. one muhapula chinhu chochose kwa zina jangu nizamtendelani. yesu '
b'kamulongela petili, "bweleza zele jako muna iyala. "ufalume wa kuulanga ulinga vino. niye mulala mula'
b'ngulizi, nokwandikila weye gayo mulondwa wangu yonikulonda muna ikweli. nomulongelani ukweli, munhu y'
b'oyose yohauhokela ufalume wa mulungu fana mwana mdoododo, hezakwingila muna ufalume uwo ng\'o!" iyo ni'


In [27]:
def split_input_target(sequence):
    input_text = sequence[:-1]
    target_text = sequence[1:]
    return input_text, target_text

In [28]:
split_input_target(list("Tensorflow"))


(['T', 'e', 'n', 's', 'o', 'r', 'f', 'l', 'o'],
 ['e', 'n', 's', 'o', 'r', 'f', 'l', 'o', 'w'])

In [29]:
dataset = sequences.map(split_input_target)


In [30]:
for input_example, target_example in dataset.take(1):
    print("Input :", text_from_ids(input_example).numpy())
    print("Target:", text_from_ids(target_example).numpy())

Input : b"chikale vinogile fana viya wanhu wochikala habung'huke imisi, si kwa umelo na ung'waji na unyolodo n"
Target: b"hikale vinogile fana viya wanhu wochikala habung'huke imisi, si kwa umelo na ung'waji na unyolodo na"


2022-10-26 17:15:59.557607: W tensorflow/core/platform/profile_utils/cpu_utils.cc:128] Failed to get CPU frequency: 0 Hz


In [31]:
# Batch size
BATCH_SIZE = 64

# Buffer size to shuffle the dataset
# (TF data is designed to work with possibly infinite sequences,
# so it doesn't attempt to shuffle the entire sequence in memory. Instead,
# it maintains a buffer in which it shuffles elements).
BUFFER_SIZE = 10000

dataset = (
    dataset
    .shuffle(BUFFER_SIZE)
    .batch(BATCH_SIZE, drop_remainder=True)
    .prefetch(tf.data.experimental.AUTOTUNE))

dataset

<PrefetchDataset element_spec=(TensorSpec(shape=(64, 100), dtype=tf.int64, name=None), TensorSpec(shape=(64, 100), dtype=tf.int64, name=None))>

In [32]:
# Length of the vocabulary in StringLookup Layer
vocab_size = len(ids_from_chars.get_vocabulary())

# The embedding dimension
embedding_dim = 256

# Number of RNN units
rnn_units = 1024

In [33]:
class Model(tf.keras.Model):
    def __init__(self, char_size, embedding_size, run_units):
        super().__init__(self)
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)

In [34]:
class MyModel(tf.keras.Model):
    def __init__(self, vocab_size, embedding_dim, rnn_units):
        super().__init__(self)
        self.embedding = tf.keras.layers.Embedding(vocab_size, embedding_dim)
        self.gru = tf.keras.layers.GRU(rnn_units,
                                       return_sequences=True,
                                       return_state=True)
        self.dense = tf.keras.layers.Dense(vocab_size)

    def call(self, inputs, states=None, return_state=False, training=False):
        x = inputs
        x = self.embedding(x, training=training)
        if states is None:
            states = self.gru.get_initial_state(x)
        x, states = self.gru(x, initial_state=states, training=training)
        x = self.dense(x, training=training)

        if return_state:
            return x, states
        else:
            return x

In [35]:
model = MyModel(
    vocab_size=vocab_size,
    embedding_dim=embedding_dim,
    rnn_units=rnn_units)

In [36]:
for input_example_batch, target_example_batch in dataset.take(1):
    example_batch_predictions = model(input_example_batch)
    print(example_batch_predictions.shape, "# (batch_size, sequence_length, vocab_size)")
    

(64, 100, 49) # (batch_size, sequence_length, vocab_size)


In [37]:
model.summary()

Model: "my_model"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       multiple                  12544     
                                                                 
 gru (GRU)                   multiple                  3938304   
                                                                 
 dense (Dense)               multiple                  50225     
                                                                 
Total params: 4,001,073
Trainable params: 4,001,073
Non-trainable params: 0
_________________________________________________________________


In [38]:
sampled_indices = tf.random.categorical(example_batch_predictions[0], num_samples=1)
sampled_indices = tf.squeeze(sampled_indices, axis=-1).numpy()

In [39]:
print("Input:\n", text_from_ids(input_example_batch[0]).numpy())
print()
print("Next Char Predictions:\n", text_from_ids(sampled_indices).numpy())

Input:
 b" kuilumba na chiilisito yesu. chila siku kwa moyo umwe wagendelela kuiting'hana hamwe muna ikaye ya "

Next Char Predictions:
 b":ntnv;eag7q;;z9fbe-y;ys7p3';-tpqc8cwarr-i42'jsfu-s66'hwewl[UNK]w!(1(z!a07h6?s5j4'8lt?7k:f;zh'8w![UNK]7a'x18."


In [40]:
loss = tf.losses.SparseCategoricalCrossentropy(from_logits=True)

In [41]:
example_batch_mean_loss = loss(target_example_batch, example_batch_predictions)
print("Prediction shape: ", example_batch_predictions.shape, " # (batch_size, sequence_length, vocab_size)")
print("Mean loss:        ", example_batch_mean_loss)

Prediction shape:  (64, 100, 49)  # (batch_size, sequence_length, vocab_size)
Mean loss:         tf.Tensor(3.890995, shape=(), dtype=float32)


In [42]:
tf.exp(example_batch_mean_loss).numpy()

48.959576

In [43]:
model.compile(optimizer='adam', loss=loss)


In [44]:
# Directory where the checkpoints will be saved
checkpoint_dir = './training_checkpoints'
# Name of the checkpoint files
checkpoint_prefix = os.path.join(checkpoint_dir, "ckpt_{epoch}")

checkpoint_callback = tf.keras.callbacks.ModelCheckpoint(
    filepath=checkpoint_prefix,
    save_weights_only=True)

In [45]:
EPOCHS = 20


In [46]:
history = model.fit(dataset, epochs=EPOCHS, callbacks=[checkpoint_callback])

Epoch 1/20


2022-10-26 17:16:03.875357: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-26 17:16:04.204943: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-26 17:16:04.560462: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


93/93 [==============================] - 19s 184ms/step - loss: 2.6639
Epoch 2/20
93/93 [==============================] - 17s 184ms/step - loss: 1.9445
Epoch 3/20
93/93 [==============================] - 17s 184ms/step - loss: 1.8115
Epoch 4/20
93/93 [==============================] - 17s 184ms/step - loss: 1.6951
Epoch 5/20
93/93 [==============================] - 17s 184ms/step - loss: 1.5721
Epoch 6/20
93/93 [==============================] - 17s 184ms/step - loss: 1.4626
Epoch 7/20
93/93 [==============================] - 17s 184ms/step - loss: 1.3626
Epoch 8/20
93/93 [==============================] - 17s 183ms/step - loss: 1.2718
Epoch 9/20
93/93 [==============================] - 17s 183ms/step - loss: 1.2003
Epoch 10/20
93/93 [==============================] - 17s 183ms/step - loss: 1.1426
Epoch 11/20
93/93 [==============================] - 17s 183ms/step - loss: 1.0918
Epoch 12/20
93/93 [==============================] - 17s 184ms/step - loss: 1.0445
Epoch 13/20
93/93 [=====

In [61]:
class OneStep(tf.keras.Model):
  def __init__(self, model, chars_from_ids, ids_from_chars, temperature=1.0):
    super().__init__()
    self.temperature = temperature
    self.model = model
    self.chars_from_ids = chars_from_ids
    self.ids_from_chars = ids_from_chars

    # Create a mask to prevent "[UNK]" from being generated.
    skip_ids = self.ids_from_chars(['[UNK]'])[:, None]
    sparse_mask = tf.SparseTensor(
        # Put a -inf at each bad index.
        values=[-float('inf')]*len(skip_ids),
        indices=skip_ids,
        # Match the shape to the vocabulary
        dense_shape=[len(ids_from_chars.get_vocabulary())])
    self.prediction_mask = tf.sparse.to_dense(sparse_mask)

  @tf.function
  def generate_one_step(self, inputs, states=None):
    # Convert strings to token IDs.
    input_chars = tf.strings.unicode_split(inputs, 'UTF-8')
    input_ids = self.ids_from_chars(input_chars).to_tensor()

    # Run the model.
    # predicted_logits.shape is [batch, char, next_char_logits]
    predicted_logits, states = self.model(inputs=input_ids, states=states,
                                          return_state=True)
    # Only use the last prediction.
    predicted_logits = predicted_logits[:, -1, :]
    predicted_logits = predicted_logits/self.temperature
    # Apply the prediction mask: prevent "[UNK]" from being generated.
    predicted_logits = predicted_logits + self.prediction_mask

    # Sample the output logits to generate token IDs.
    predicted_ids = tf.random.categorical(predicted_logits, num_samples=1)
    predicted_ids = tf.squeeze(predicted_ids, axis=-1)

    # Convert from token ids to characters
    predicted_chars = self.chars_from_ids(predicted_ids)

    # Return the characters and model state.
    return predicted_chars, states

  @tf.function
  def generate_one_step_probablity(self, inputs, states=None):
    # Convert strings to token IDs.
    input_chars = tf.strings.unicode_split(inputs, 'UTF-8')
    input_ids = self.ids_from_chars(input_chars).to_tensor()

    # Run the model.
    # predicted_logits.shape is [batch, char, next_char_logits]
    predicted_logits, states = self.model(inputs=input_ids, states=states,
                                          return_state=True)
    # Only use the last prediction.
    predicted_logits = predicted_logits[:, -1, :]
    predicted_logits = predicted_logits/self.temperature
    # Apply the prediction mask: prevent "[UNK]" from being generated.
    predicted_logits = predicted_logits + self.prediction_mask

#     Sample the output logits to generate token IDs.
    predicted_ids = tf.random.categorical(predicted_logits, num_samples=1)
    predicted_ids = tf.squeeze(predicted_ids, axis=-1)

    # Convert from token ids to characters
    predicted_chars = self.chars_from_ids(predicted_ids)

    # Return the characters and model state.
    return predicted_chars, predicted_logits, states

In [62]:
one_step_model = OneStep(model, chars_from_ids, ids_from_chars)

In [63]:
start = time.time()
states = None
next_char = tf.constant(['R'])
result = [next_char]

for n in range(1000):
    next_char, states = one_step_model.generate_one_step(next_char, states=states)
    result.append(next_char)

result = tf.strings.join(result)
end = time.time()
print(result[0].numpy().decode('utf-8'), '\n\n' + '_'*80)
print('\nRun time:', end - start)

2022-10-26 18:01:26.154630: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-26 18:01:26.197264: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-26 18:01:26.463994: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-26 18:01:26.503845: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


Rza wasaha zenu wanhu wa mulungu. munhu yoyose kabule mbaka yayo zowapeteleni mbuli inogile. mweye wose wowamanyilekule fana viyeli na mulungu. "lnga kwa mndewa mulungu kakala yaja yoyolonda mulungu, yesu hachidahile kukongela viyakulondele, yachigese muna dizawe da kutandikila na lukali, na tati yangu, kezavilaganika kwa uuloma ugola. sauli kamuuza petili, "nzewulogda. kulawa muke ni utunhizo wake, na kutenda yehile kamwilila mgdulu na kumgwila kezalokigwa na kukala muna ikaye ya mulungu wa sambi na beho kulu muna ufulumwe wohoiyohi.  bali weye na mukofo wezakuwa nawo kwa kusonhela uhuwilo wawo. chino niicho chose kwa zina jangw. walondwa, sekewaze wokwingila muna dibululu jawo na wandusa kutenda yaja vimfiligu.eka nanga yakale hhugulo kilagusogwa kwa tata, yezumbanangela uko. lekamaabaho petili na chino anigune muhasanyi kufosa wamwenga mabana goya ng'hali kaisaliya hamwe hawaifundizeni, mbali wanahina wake wahita kuna digulilo. kwaviya nolonga na wanhu wanogile na yauko s uba, kanil

In [65]:
loss = 0 

start = time.time()
states = None
next_char = tf.constant(['r'])
result = []

total_loss_list = []
for n in range(100):
    next_char, next_probablity, states = one_step_model.generate_one_step_probablity(next_char, states=states)
    total_loss_list.append(-np.log2(max(tf.nn.softmax(next_probablity.numpy()[0], axis=None))))
    result.append(next_probablity)

# result = tf.strings.join(result)
end = time.time()
# print(result[0].numpy().decode('utf-8'), '\n\n' + '_'*80)
# print('\nRun time:', end - start)



In [68]:
np.mean(total_loss_list)

0.6986373

In [54]:
# loss_from_scratch -= log2(from_scratch_model(lang, c, history))

max(tf.nn.softmax(
    result[3][0].numpy(), axis=None, name=None
))

<tf.Tensor: shape=(), dtype=float32, numpy=0.07408987>

In [57]:
max(tf.nn.softmax(
    result[3].numpy(), axis=None, name=None
))

<tf.Tensor: shape=(49,), dtype=float32, numpy=
array([0.        , 0.02845919, 0.00983365, 0.0284922 , 0.01398859,
       0.00902915, 0.0072718 , 0.01143145, 0.00573098, 0.0060695 ,
       0.00943579, 0.00968499, 0.00921553, 0.00931626, 0.00849468,
       0.00843143, 0.00721691, 0.00883537, 0.00958114, 0.00881471,
       0.00655271, 0.00913829, 0.00580503, 0.01699818, 0.01948233,
       0.03423317, 0.01799148, 0.02631748, 0.04853597, 0.01228855,
       0.02998772, 0.05253309, 0.0217478 , 0.03854892, 0.03795702,
       0.07408987, 0.04586774, 0.03412191, 0.02797083, 0.00885706,
       0.0083934 , 0.03271928, 0.02636588, 0.0192988 , 0.04898583,
       0.02804727, 0.00986839, 0.03024971, 0.01771308], dtype=float32)>

In [45]:
start = time.time()
states = None
next_char = tf.constant(['R', 'R', 'R', 'R', 'R'])
result = [next_char]

for n in range(1000):
  next_char, states = one_step_model.generate_one_step(next_char, states=states)
  result.append(next_char)

result = tf.strings.join(result)
end = time.time()
print(result, '\n\n' + '_'*80)
print('\nRun time:', end - start)

2022-10-25 14:57:37.688264: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-25 14:57:37.757019: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-25 14:57:37.997745: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-25 14:57:38.038844: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


tf.Tensor(
[b'Rbulizi wa bululu. yano viyahalike kupotigwa na ndugu zako wezadilemela bule. viwakomeleze kumkumbu na mwanage kuyotela. ivo mulungu kotaza kwa mulungu, komuhitila masodika, na iviya waja yolonga kuwa nolonga na kumwingila munhu ino. wopeta matumbala mote yadenganike wakala wahulika hbulu yake, na inikona kukonhela mweye kwa mbuli yoyose, muladi yaloneeehimawa na welasigwa? yesu kamuhonyanhu haja hachihondigwe muulongo na kufosela muulumita. baho niya ndima yotangigwa "mbuli ya wfulungu, nikumbasafunyo ng\'o, vino mulungu kakala kolonga nawo wamfungta. mbali chiumono na yoyandikigwe mwanza umwenga na makanduku hamwe na lukali. wanhu wose wezamuwona hanhu hondu yohanda. ipangi yoyaninogeligwe, yoisafykkani mweye wenyewo kumwetu wiza na kugong\'onda ukala mogololeni mayoja na kusondelela malungu. yesu kawahonya wetu na koilanga yano yoyayatangigwe udaho wa mndewa, mbali wakala wokolola weye kwawichiwona, na wasang\'hani wa weye, fana viyilonda mulungu tati yetu yelu mgelonk

In [46]:
tf.saved_model.save(one_step_model, 'one_step')
one_step_reloaded = tf.saved_model.load('one_step')

2022-10-25 14:57:44.926878: W tensorflow/python/util/util.cc:368] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.


INFO:tensorflow:Assets written to: one_step/assets


INFO:tensorflow:Assets written to: one_step/assets
2022-10-25 14:57:52.268971: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-25 14:57:52.274489: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


In [47]:
states = None
next_char = tf.constant(['chond'])
result = [next_char]

for n in range(100):
  next_char, states = one_step_reloaded.generate_one_step(next_char, states=states)
  result.append(next_char)

print(tf.strings.join(result)[0].numpy().decode("utf-8"))

2022-10-25 14:57:52.310306: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-25 14:57:52.401095: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-25 14:57:52.524702: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.
2022-10-25 14:57:52.587841: I tensorflow/core/grappler/optimizers/custom_graph_optimizer_registry.cc:113] Plugin optimizer for device_type GPU is enabled.


chonde cholonda kulonga, sekeyamulolele mulungu yoyowatenda wano wawotambwanw  ndugu zangu." saabi moto m
